### ISSUE TITLE
[GitLab] cannot be called inside a transaction as this can lead to race conditions when the worker runs before the transaction is committed and tries to access a model that has not been saved ye

### ISSUE THREAD

**Issue by unaheidi** [unaheidi/it_ga_la#2]

**Comment by unaheidi** [comment]
### 新建 Group 报错：  
```
  SQL (0.6ms)  INSERT INTO "routes" ("source_id", "source_type", "path", "created_at", "updated_at", "name") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["source_id", 14], ["source_type", "Namespace"], ["path", "books"], ["created_at", "2019-09-11 02:09:54.578475"], ["updated_at", "2019-09-11 02:09:54.578475"], ["name", "books"]]
  ↳ app/services/groups/create_service.rb:26
  SQL (6.1ms)  DELETE FROM "redirect_routes" WHERE (LOWER(redirect_routes.path) = LOWER('books') OR LOWER(redirect_routes.path) LIKE LOWER('books/%'))
  ↳ app/models/route.rb:54
   (0.5ms)  ROLLBACK
  ↳ app/services/groups/create_service.rb:26
Completed 500 Internal Server Error in 68ms (ActiveRecord: 17.8ms)



Sidekiq::Worker::EnqueueFromTransactionError - `NotifyHermesWorker.perform_async` cannot be called inside a transaction as this can lead to
race conditions when the worker runs before the transaction is committed and
tries to access a model that has not been saved yet.

Use an `after_commit` hook, or include `AfterCommitQueue` and use a `run_after_commit` block instead.
:
  config/initializers/forbid_sidekiq_in_transactions.rb:22:in `block (2 levels) in <module:NoEnqueueingFromTransactions>'
  app/services/groups/create_service.rb:26:in `execute'
  lib/gitlab/metrics/instrumentation.rb:161:in `block in execute'
  lib/gitlab/metrics/method_call.rb:36:in `measure'
  lib/gitlab/metrics/instrumentation.rb:161:in `execute'
  app/controllers/groups_controller.rb:44:in `create'
  lib/gitlab/i18n.rb:55:in `with_locale'
  lib/gitlab/i18n.rb:61:in `with_user_locale'
  app/controllers/application_controller.rb:421:in `set_locale'
  lib/gitlab/middleware/multipart.rb:103:in `call'
  lib/gitlab/request_profiler/middleware.rb:16:in `call'
  lib/gitlab/query_limiting/middleware.rb:17:in `block in call'
  lib/gitlab/query_limiting/transaction.rb:39:in `run'
  lib/gitlab/query_limiting/middleware.rb:16:in `call'
  lib/gitlab/middleware/go.rb:19:in `call'
  lib/gitlab/etag_caching/middleware.rb:13:in `call'
  lib/gitlab/middleware/correlation_id.rb:16:in `block in call'
  lib/gitlab/correlation_id.rb:15:in `use_id'
  lib/gitlab/middleware/correlation_id.rb:15:in `call'
  lib/gitlab/middleware/rails_queue_duration.rb:24:in `call'
  lib/gitlab/metrics/rack_middleware.rb:17:in `block in call'
  lib/gitlab/metrics/transaction.rb:55:in `run'
  lib/gitlab/metrics/rack_middleware.rb:17:in `call'
  lib/gitlab/middleware/read_only/controller.rb:40:in `call'
  lib/gitlab/middleware/read_only.rb:18:in `call'
  lib/gitlab/middleware/basic_health_check.rb:25:in `call'
  lib/gitlab/request_context.rb:20:in `call'
  lib/gitlab/middleware/static.rb:11:in `call'
  lib/gitlab/metrics/requests_rack_middleware.rb:29:in `call'
  lib/gitlab/middleware/release_env.rb:13:in `call'
```
chrome显示信息：  
![image](https://user-images.githubusercontent.com/4635811/64663116-57c46500-d47d-11e9-8d51-fdb75071cde2.png)

**Comment by unaheidi** [comment]
* 遇到上面的问题，真希望有debug工具可以来定位究竟是哪里出故障了。  
* 在 ruby 文件里面只需在需要跟踪代码的地方，添加 binding.pry 即可。[参考资料](https://docs.gitlab.com/ee/development/pry_debugging.html) 。
* 当然，rails 服务需要使用 rails s 启动，而不用 /etc/init.d/gitlab start 启动。运行的服务日志可以在console中输出，并能在console中debug代码。
* debug遇到的迷，目前还没有搞定：  
  * 在 app/controllers/group_controller.rb 44行增加 binding.pry 
```ruby
  def create
      binding.pry 
```
  * 通过 next 和 step 命令，
```ruby
  [1] pry(#<Groups::CreateService>)> next

From: /Users/git/gitlab/app/services/groups/create_service.rb @ line 26 Groups::CreateService#execute:

    10: def execute
    11:   @group = Group.new(params)
    12:
    13:   unless can_use_visibility_level? && can_create_group?
    14:     return @group
    15:   end
    16:
    17:   @group.name ||= @group.path.dup
    18:
    19:   if create_chat_team?
    20:     response = Mattermost::CreateTeamService.new(@group, current_user).execute
    21:     return @group if @group.errors.any?
    22:
    23:     @group.build_chat_team(name: response['name'], team_id: response['id'])
    24:   end
    25:
 => 26:   @group.save
    27:   @group.add_owner(current_user)
    28:   @group
    29: end
```  
```ruby
  [1] pry(#<Groups::CreateService>)> next

From: /Users/git/gitlab/app/services/groups/create_service.rb @ line 26 Groups::CreateService#execute:

    10: def execute
    11:   @group = Group.new(params)
    12:
    13:   unless can_use_visibility_level? && can_create_group?
    14:     return @group
    15:   end
    16:
    17:   @group.name ||= @group.path.dup
    18:
    19:   if create_chat_team?
    20:     response = Mattermost::CreateTeamService.new(@group, current_user).execute
    21:     return @group if @group.errors.any?
    22:
    23:     @group.build_chat_team(name: response['name'], team_id: response['id'])
    24:   end
    25:
 => 26:   @group.save
    27:   @group.add_owner(current_user)
    28:   @group
    29: end

[1] pry(#<Groups::CreateService>)> step

From: /Users/git/gitlab/vendor/bundle/gems/activerecord-5.0.7/lib/active_record/suppressor.rb @ line 41 ActiveRecord::Suppressor#save:

    40: def save(*) # :nodoc:
 => 41:   SuppressorRegistry.suppressed[self.class.name] ? true : super
    42: end

[1] pry(#<Group>)> step

From: /Users/git/gitlab/vendor/bundle/gems/activesupport-5.0.7/lib/active_support/per_thread_registry.rb @ line 53 ActiveRecord::SuppressorRegistry.suppressed:

 => 53: singleton_class.delegate name, to: :instance

[1] pry(ActiveRecord::SuppressorRegistry)> step

From: /Users/git/gitlab/vendor/bundle/gems/activesupport-5.0.7/lib/active_support/per_thread_registry.rb @ line 45 ActiveSupport::PerThreadRegistry#instance:

    44: def instance
 => 45:   Thread.current[@per_thread_registry_key] ||= new
    46: end

[1] pry(ActiveRecord::SuppressorRegistry)> step
```  
debug捣腾来捣腾去，居然被我创建出了一个 Group 出来，正常情况创建 Group是报错的。  

暂时做个记录。
