### ISSUE TITLE
[GitLab] 写代码之前得搞定环境问题

### ISSUE THREAD

**Issue by unaheidi** [unaheidi/it_ga_la#4]
### 前言
在 Mac OS 上根据 [前人笔记](https://github.com/WebEntity/Installation-guide-for-GitLab-on-OS-X) ，终于把 GitLab 的 web 服务给运行起来了。  

以为这样就搞定环境问题了，那就太乐观了。得看看下面的功能是否可以：  
* 能创建 group 和 project 吗？
* 能通过http的方式clone仓库吗？
* 能通过ssh的方式clone仓库吗？

搞笑的是：上面的每一项我都遇到了问题。

### ssh clone仓库遇到的问题
* 报connect问题，原来是Mac上没有启用ssh服务。
* 用户的公钥根本没有写入 /Users/git/.ssh/authorization_keys 文件中
   想[Rebuild authorized_keys file](https://docs.gitlab.com/ee/administration/raketasks/maintenance.html)，又遇到 rake 报错：  
```ruby
bash-3.2$ bundle exec rake   gitlab:shell:setup RAILS_ENV=development
rake aborted!
LoadError: incompatible library version - /Users/git/gitlab/vendor/bundle/gems/concurrent-ruby-ext-1.1.5/lib/concurrent/concurrent_ruby_ext.bundle
/Users/git/gitlab/vendor/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/Users/git/gitlab/vendor/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/Users/git/gitlab/vendor/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/git/gitlab/vendor/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/Users/git/gitlab/vendor/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
```

然后又报下面的错：  
```ruby
Caused by:
LoadError: cannot load such file -- nokogiri/2.5/nokogiri
```

```ruby
执行 bundle exec rails s --port=8080 后报错
/Users/git/gitlab/vendor/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require': incompatible library version - /Users/git/gitlab/vendor/bundle/gems/nokogiri-1.8.5/lib/nokogiri/nokogiri.bundle (LoadError)
```

```ruby
Fetching: nokogiri-1.3.3.gem (100%)
Building native extensions. This could take a while...
ERROR:  Error installing nokogiri:
	ERROR: Failed to build gem native extension.

    current directory: /Users/git/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/nokogiri-1.3.3/ext/nokogiri
/Users/git/.rbenv/versions/2.5.3/bin/ruby -r ./siteconf20190912-34291-1bygwnk.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/git/.rbenv/versions/2.5.3/bin/$(RUBY_BASE_NAME)
extconf.rb:8:in `<main>': uninitialized constant Config (NameError)
Did you mean?  RbConfig
               CONFIG

extconf failed, exit code 1

Gem files will remain installed in /Users/git/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/nokogiri-1.3.3 for inspection.
Results logged to /Users/git/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-16/2.5.0-static/nokogiri-1.3.3/gem_make.out
```

**Comment by unaheidi** [comment]
中秋节后继续解决环境问题  
* rbenv uninstall 2.5.3
* 参考[Mac 安装文档](https://github.com/WebEntity/Installation-guide-for-GitLab-on-OS-X)重新安装 ruby 2.5.3 版本。
* 报bundle相关的错误，根据[参考资料](https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html)安装了 Gemfile.lock 中指定的版本。
* 执行 rake 仍然报错  

***怎么办呢？***
* 还有一招，删除 /Users/git/gitlab/vendor/bundle 路径
* 重新执行 bundle install

> * 通过上面的处理后，终于把 ruby和rake的执行环境给恢复回来了。
> * rake执行环境坏掉的问题，估计和我运行了 bundle update 有关。
> * 然后继续执行下面的任务：
```ruby
bash-3.2$ bundle exec rake   gitlab:shell:setup RAILS_ENV=development
```

**Comment by unaheidi** [comment]
* 我们看看 https://github.com/unaheidi/it_ga_la/issues/4#issuecomment-531634309 提及的执行效果吧。会不会又出其他幺蛾子？ 😆 
```ruby
bash-3.2$ bundle exec rake gitlab:shell:setup RAILS_ENV=development
(in /Users/git/gitlab)
/Users/git/gitlab/ctrip/lib/tasks/gitlab/elastic.rake:61: warning: already initialized constant INDEXABLE_CLASSES
/Users/git/gitlab/ctrip/lib/tasks/gitlab/elastic.rake:61: warning: previous definition of INDEXABLE_CLASSES was here
This task will now rebuild the authorized_keys file.
You will lose any data stored in the authorized_keys file.
Do you want to continue (yes/no)? yes

.
Failed to add keys...
bash-3.2$
```
嘿嘿，又出现问题了！

**Comment by unaheidi** [comment]
* 在查问题的过程中，发现诡异的现象：明明把 /Users/git/ 路径的 group 都设置为 git 了，但是，过不了多久，group会重新变回 daemon。 
```shell
bash-3.2$ pwd
/Users/git/gitlab/vendor
bash-3.2$ ls -al
total 248
drwxr-xr-x   15 git  daemon    510  9 16 12:13 .
drwxr-xr-x   81 git  daemon   2754  9 16 12:12 ..
drwxr-xr-x   21 git  daemon    714  8 28 10:33 Dockerfile
drwxr-xr-x    4 git  daemon    136  8 28 10:33 assets
drwxr-xr-x   10 git  daemon    340  9 16 12:22 bundle
drwxr-xr-x   10 git  daemon    340  9 16 11:02 bundle_bak
drwxr-xr-x    4 git  daemon    136  8 28 10:33 cert_manager
drwxr-xr-x  130 git  daemon   4420  8 28 10:33 gitignore
drwxr-xr-x    3 git  daemon    102  8 28 10:33 ingress
drwxr-xr-x    3 git  daemon    102  8 28 10:33 jupyter
-rwxr-xr-x    1 git  daemon  91888  8 28 10:33 languages.yml
-rw-r--r--    1 git  daemon  28849  8 28 10:33 licenses.csv
drwxr-xr-x    5 git  daemon    170  8 28 10:33 project_templates
drwxr-xr-x    3 git  daemon    102  8 28 10:33 prometheus
drwxr-xr-x    3 git  daemon    102  8 28 10:33 runner
```

* 用 dscl 命令后，发现 git 这个 group 的 ID 有问题。
```bash
dst63282:~ suling$ dscl . -list /Groups PrimaryGroupID
consoleusers                              53
daemon                                    1
dialer                                    68
everyone                                  12
git                                       1
group                                     16
interactusers                             51
kmem                                      2
localaccounts                             61
```

**Comment by unaheidi** [comment]
那么， 把 git 这个 group 的 ID 搞定后，执行 `gitlab:shell:setup` 这个就ok了呢？  
* 用 binding.pry 重新跟踪代码的运行 , 发现 io.puts("#{id}\t#{key}") 报错：
```ruby
From: /Users/git/gitlab/lib/gitlab/shell.rb @ line 21 Gitlab::Shell::KeyAdder#add_key:

    14: def add_key(id, key)
    15:   key = Gitlab::Shell.strip_key(key)
    16:   # Newline and tab are part of the 'protocol' used to transmit id+key to the other end
    17:   if key.include?("\t") || key.include?("\n")
    18:     raise Error.new("Invalid key: #{key.inspect}")
    19:   end
    20:
 => 21:   io.puts("#{id}\t#{key}")
    22: end

[14] pry(#<Gitlab::Shell::KeyAdder>)> io.class
=> IO
[15] pry(#<Gitlab::Shell::KeyAdder>)> io.class.class
=> Class
[16] pry(#<Gitlab::Shell::KeyAdder>)> io.class.class.class
=> Class
[17] pry(#<Gitlab::Shell::KeyAdder>)> io.pipe
NoMethodError: undefined method `pipe' for #<IO:fd 19>
from (pry):15:in `add_key'
[18] pry(#<Gitlab::Shell::KeyAdder>)> io.puts("a")
Errno::EPIPE: Broken pipe
from (pry):16:in `write'
[19] pry(#<Gitlab::Shell::KeyAdder>)> continue
rake aborted!
Errno::EPIPE: Broken pipe
```
* 查看运行的日志
```ruby
bash-3.2$ pwd
/Users/git/gitlab/log
bash-3.2$ tail -n50 development.log
  ActiveRecord::SchemaMigration Load (0.6ms)  SELECT "schema_migrations".* FROM "schema_migrations"
ActiveRecord connection established
Creating scope :of_projects. Overwriting existing method MergeRequest.of_projects.
Creating scope :join_project. Overwriting existing method MergeRequest.join_project.
Creating scope :references_project. Overwriting existing method MergeRequest.references_project.
Creating scope :system. Overwriting existing method Note.system.
Creating scope :created. Overwriting existing method Ci::Stage.created.
Creating scope :pending. Overwriting existing method Ci::Stage.pending.
Creating scope :running. Overwriting existing method Ci::Stage.running.
Creating scope :success. Overwriting existing method Ci::Stage.success.
Creating scope :failed. Overwriting existing method Ci::Stage.failed.
Creating scope :canceled. Overwriting existing method Ci::Stage.canceled.
Creating scope :skipped. Overwriting existing method Ci::Stage.skipped.
Creating scope :manual. Overwriting existing method Ci::Stage.manual.
Creating scope :scheduled. Overwriting existing method Ci::Stage.scheduled.
Creating scope :fresh. Overwriting existing method ProjectSnippet.fresh.
Creating scope :visible. Overwriting existing method Service.visible.
Creating scope :order_name_asc. Overwriting existing method Member.order_name_asc.
Creating scope :order_name_desc. Overwriting existing method Member.order_name_desc.
Creating scope :order_name_asc. Overwriting existing method Label.order_name_asc.
Creating scope :order_name_desc. Overwriting existing method Label.order_name_desc.
Creating scope :system. Overwriting existing method PrometheusMetric.system.
  Key Load (2.2ms)  SELECT  "keys".* FROM "keys" ORDER BY "keys"."id" ASC LIMIT $1  [["LIMIT", 1000]]
  ↳ lib/tasks/gitlab/shell.rake:108
Broken pipe excluded from capture: DSN not set
  ApplicationSetting Load (1.0ms)  SELECT  "application_settings".* FROM "application_settings" ORDER BY "application_settings"."id" DESC LIMIT $1  [["LIMIT", 1]]
  ActiveRecord::SchemaMigration Load (0.7ms)  SELECT "schema_migrations".* FROM "schema_migrations"
ActiveRecord connection established
Creating scope :of_projects. Overwriting existing method MergeRequest.of_projects.

```
* 关键信息终于出现了 Broken pipe excluded from capture: DSN not set

**Comment by unaheidi** [comment]
根据关键信息到 Google 上查找有用的信息，虽然结果寥寥，但还是找到一篇可能有用的文章：
https://docs.gitlab.com/ee/ssh/README.html#troubleshooting 。仔细看看是不是有帮助。

* 没有什么帮助，但检查了 sshd 服务是在运行的。
* 再去官网看看source安装指南。
   * 发现 /Users/git/gitlab/log 权限和官网的不同。需增加执行 `chmod -R u+rwx,go-w log/`

**Comment by unaheidi** [comment]
command="/var/apps/gitlab-shell/bin/gitlab-shell",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa

**Comment by unaheidi** [comment]
核对了官网的安装步骤，也调整了部门文件夹的权限，可是仍然报 ```Errno::EPIPE: Broken pipe```错。

**Comment by unaheidi** [comment]
怎么办？```Broken pipe excluded from capture: DSN not set``` 合适的参考资料几乎没有。  
要不，手工把 ```~/.ssh/authorized_keys``` 填入用户的公钥，然后用ssh clone仓库试试看？

总不能一点进展都没有吧。

**Comment by unaheidi** [comment]
说干就干，看 git clone 的命令，终于有点新气象了。
```ruby
localhost:tmp Unaheidi$ git clone http://localhost:8080/root/nodejs-ex100.git
Cloning into 'nodejs-ex100'...
/Users/git/gitlab-shell/lib/gitlab_net.rb:155:in `parse_who': who='' is invalid! (ArgumentError)
	from /Users/git/gitlab-shell/lib/gitlab_shell.rb:33:in `initialize'
	from /Users/git/gitlab-shell/bin/gitlab-shell-ruby:34:in `new'
	from /Users/git/gitlab-shell/bin/gitlab-shell-ruby:34:in `<main>'
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by unaheidi** [comment]
然后再通过 bing 搜索关键字 “gitlab authorized_keys”，居然有惊喜！！！  
有必要认真读一读 [fast ssh key lookup 的文档](https://docs.gitlab.com/ee/administration/operations/fast_ssh_key_lookup.html)  

读完后，发现该文档并不能直接解决我们的问题，它讲解如何提高公钥查找的效率。  
然而，和公司负责GitLab开发的同事聊 fast ssh key lookup  这个话题的时候，居然把我遇到问题的原因给找到了。真是“柳暗花明又一村” 。:sunny: :congratulations:

原来我们实现 Gitlab Sharding 功能的时候，早就把用户的公钥存入数据库里了，因此，开发人员把修改 
authorization_keys 的相关逻辑去掉了。  

在 Gitlab 开发环境中，因为我没有配置 Sharding 所需的 proxy 服务，所以，我得把恢复 authorization_keys 变更的逻辑。

```ruby gitlab_keys.rb
  def exec
    GitlabMetrics.measure("command-#{@command}") do
      case @command
      when 'add-key'
        add_key   #把同事添加的注释去掉。
      when 'batch-add-keys'
        batch_add_keys  #把同事添加的注释去掉。
      when 'rm-key'
        rm_key #把同事添加的注释去掉。
      when 'list-keys'
        list_keys
      when 'list-key-ids'
        list_key_ids
      when 'clear'
        clear
      when 'check-permissions'
        check_permissions
      else
        $logger.warn('Attempt to execute invalid gitlab-keys command', command: @command.inspect)
        puts 'not allowed'
        false
      end
    end
  end

```

##### 经过上面的处理，终于搞定了 ssh 的 clone 功能。

**Comment by unaheidi** [comment]
[14] pry(main)> a.method(:batch_add_keys).source_location
=> ["/Users/git/gitlab/lib/gitlab/metrics/instrumentation.rb", 158]

**Comment by unaheidi** [comment]
#### ruby
```ruby
Gitlab::Shell.instance_methods.include?(:batch_add_keys)
Gitlab::Shell.new.methods.include?(:batch_add_keys)
```

**Comment by unaheidi** [comment]
#### check if a method has been instrumented is to check its source location
```ruby
[8] pry(main)> Gitlab::Shell.new.method(:batch_add_keys).source_location
=> ["/Users/git/gitlab/lib/gitlab/metrics/instrumentation.rb", 159]
```

#### 参考资料
https://docs.gitlab.com/ee/development/instrumentation.html

**Comment by unaheidi** [comment]
#### 以上基本上和 gitlab + gitlab-shell 打交道
#### 接下去我们得看看 http 协议clone仓库的情况了

**Comment by unaheidi** [comment]
🦀 会不会又遇到坑呢？  😆  😆 😆

#### 真高兴，又报错了
**Git客户端报**
```ruby
$ git clone  http://localhost:8080/root/nodejs-ex100.git  node_http3
Cloning into 'node_http3'...
remote: JWT::DecodeError at /root/nodejs-ex100.git/info/refs
remote: ====================================================
```
**GitLab web服务报**
```ruby
[3] pry(#<Projects::GitHttpController>)> continue
Completed 500 Internal Server Error in 785551ms (ActiveRecord: 2.3ms)
JWT::DecodeError - Nil JSON web token:
  lib/gitlab/workhorse.rb:195:in `decode_jwt'
```

**Comment by unaheidi** [comment]
google上搜了一下，貌似和 gitlab-workhorse 有点关系。  
我记得安装 Gitlab 的时候，我把 nginx 的那部分**故意**没有做设置。

#### gitlab-workhorse 官网上介绍 
> Gitlab-workhorse is a smart reverse proxy for GitLab. It handles
"large" HTTP requests such as file downloads, file uploads, Git
push/pull and Git archive downloads.

#### 我就想看看，没有配置 nginx 
* 如[上实验](https://github.com/unaheidi/it_ga_la/issues/4#issuecomment-532151288)，ssh 的 clone 已经成功。说明 ssh 无须 nginx 。
* Gitlab走 http 的 clone 会正常吗？
> * 经过反复实验，如果没有设置 nginx ，永远报 [JWT::DecodeError - Nil JSON web token](https://github.com/unaheidi/it_ga_la/issues/4#issuecomment-532528392) 问题，且 pry 也没有发现明显的问题。
> * 于是／无奈，当下还是规规矩矩地安装 [参考文档](https://github.com/WebEntity/Installation-guide-for-GitLab-on-OS-X)  把 nginx 服务设置起来吧。

#### 正确配置好 nginx 服务后，http  下载就正常了 🌹:rose: 🌹 
回头想想，架构图中 gitlab-workhorse 和 nginx 之间的连线，看来真能说明一定的问题，反向代理服务的确需要配置。回头有机会再深入琢磨一下吧。
> ![image](https://user-images.githubusercontent.com/4635811/65206839-700e3280-dac2-11e9-985d-86cbd7ee8bdd.png)

**Comment by unaheidi** [comment]
#### gitlab-workhorse.log 报过下面的错
* 这个和 rails s 以及 /etc/init.d/gitlab 启动顺序相关
```ruby
127.0.0.1  - - [2019/09/19:10:22:52 +0800] "GET /root/nodejs-ex100.git/info/refs?service=git-upload-pack HTTP/1.1" 502 24 "" "git/2.22.0" 0.001
time="2019-09-19T10:39:10+08:00" level=error msg=error correlation_id="[MISSING]" error="badgateway: failed after 0s: dial unix /Users/git/gitlab/tmp/sockets/gitlab.socket: connect: no such file or directory" method=GET uri=
```
* 还有一个问题
```ruby
127.0.0.1  - - [2019/09/19:11:14:06 +0800] "GET /root/nodejs-ex100.git/info/refs?service=git-upload-pack HTTP/1.1" 502 24 "" "git/2.22.0" 0.004
time="2019-09-19T11:14:17+08:00" level=error msg=error correlation_id="[MISSING]" error="badgateway: failed after 0s: dial unix /Users/git/gitlab/tmp/sockets/gitlab.socket: connect: connection refused" method=GET uri=
```
##### 带着上面的问题，继续分析与思考
* 为什么 bundle exec rails s --port=8080 启动的 puma 服务， clone 总报错；而  /etc/init.d/gitlab start 启动的 unicorn 服务却正常。
*  /var/log/nginx/gitlab_error.log 为空，看着样子，nginx 已把 http clone 的请求转发给了 workhorse ，clone 502 的问题应该不是 nginx 的问题，而是 workhorse 和 gitlab rails 服务之间的问题。
* 用不同方式启动 gitlab rails 服务，结果不同，看来我们得专研一下启动 gitlab rails 服务，究竟有什么差异了。

##### 经过一番努力，终于有了些许进展。
* rails s 会默认启动 puma web服务，但是无法向 puma 传送参数。这种方式启动后，虽然可以方面的使用 pry 跟踪代码的运行，但只监听 on tcp://localhost:8080 。如下图：  
![image](https://user-images.githubusercontent.com/4635811/65225164-33106300-daf7-11e9-9c84-5bb5f969ac21.png)
* 而用 /etc/init.d/gitlab start 启动的话，执行了 bin/web start，除了监听 on tcp://localhost:8080 ，还监听了 gitlab.socket，详见 unicorn.rb 文件：
![image](https://user-images.githubusercontent.com/4635811/65227136-b1bacf80-dafa-11e9-920e-272d5e0124f4.png)
* 和  bin/web start 类似的做法，我们还可以启动定制的 puma ，但和 unicorn 一样，无法跟踪代码的运行。启动方式如下：
> * 生成 config/puma.rb 文件，自己增加了 bind 'tcp://127.0.0.1:8080' 。
```ruby
# Bind the server to "url". "tcp://", "unix://" and "ssl://" are the only
# accepted protocols.
bind 'unix:///Users/git/gitlab/tmp/sockets/gitlab.socket'
bind 'tcp://127.0.0.1:8080'
```
> * 执行 bin/web_puma start
```ruby
bash-3.2$ bin/web_puma start
[39072] Puma starting in cluster mode...
[39072] * Version 3.12.0 (ruby 2.5.3-p105), codename: Llamas in Pajamas
[39072] * Min threads: 1, max threads: 4
[39072] * Environment: development
[39072] * Process workers: 2
[39072] * Preloading application
[39072] * Listening on unix:///Users/git/gitlab/tmp/sockets/gitlab.socket
[39072] * Listening on tcp://127.0.0.1:8080
[39072] * Daemonizing...
```

* 想让 rails s 启动时给 puma 服务传送配置文件，以便启动 web 服务的同时，可以监听 socket。但是怎么都无效。
> 又表示不可行的。 [参考文档](https://github.com/puma/puma/issues/512)
> 也有表示应该可行的，但现在还有问题的   [参考文档](https://github.com/puma/puma/issues/1253)

* 我执行的环境如下：
```ruby
bash-3.2$ bundle exec rails -v
Rails 5.0.7

bash-3.2$ bundle exec gem  list | grep puma
puma (3.12.0)

```

#### 大大的惊喜！！！（后来发现是假的）
* 原本以为就这样了，rails s 启动 web 服务的时候，就无法 http 的方式 clone 仓库。
* 就是有点心不甘，情不愿。有了上面 puma 新版本介绍是可行的信息后，我还是决定再折腾一下吧。
* 现在不是只有 gitlab.socket 那边有问题吗？我们修改点其他配置项看看，看rails s的时候，config/puma.rb 这个配置文件到底会不会生效呢？
* 把 workers 2 改为 workers 3 ，发现配置文件是起作用的。但是，即使文件里面定义 bind 'unix:///Users/git/gitlab/tmp/sockets/gitlab.socket' ，但服务启动后还是没有相关的显示。到对应的路径上查看，确实没有 gitlab.socket 文件生成。
```ruby

```

**Comment by unaheidi** [comment]
#### 关了一次机器，报错了
```ruby
Started GET "/" for 127.0.0.1 at 2019-09-23 12:26:06 +0800

PG::ConnectionBad - could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
```
如果对 5432 这个端口敏感的话，估计已经猜到是数据库服务发生异常了。
安装 GitLab 服务的时候，为了用一用官方推荐的数据库，所以就采用了 postgresql 。  
这次的异常是因为关机没有删除 postmaster.pid ，重启服务失败导致的。
删除给文件后再启动服务即可。
```ruby
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
```

**Comment by unaheidi** [comment]
### GitLab web，shell，workhorse ，nginx 之间的关系
#### gitlab-shell 中有个 config.yml 配置文件，须指定 web 服务 URL 的地址，因为 gitlab-shell 需要通过 web 服务获取权限等信息。ssh 协议相关的请求，都会和 gitlab-shell 服务打交道。
```yml
gitlab_url: "http://localhost:8080" 
```     
#### nginx 和 workhorse 有紧密的联系
    nginx 的 配置文件含如下信息。
```xml
proxy_pass http://gitlab-workhorse;
```
如果 nginx 配置了 80 作为监听端口的话，那么从浏览器访问 80 端口，直接被 nginx 服务接收。nginx 则把请求转给 workhorse 。

**Comment by unaheidi** [comment]
#### 我们来做个试验
##### 前提
workhorse 进程启动信息如下：
```shell
 503  2297     1   0 11:51上午 ??         0:00.96 gitlab-workhorse -listenUmask 0 -listenNetwork unix -listenAddr /Users/git/gitlab/tmp/sockets/gitlab-workhorse.socket -authBackend http://127.0.0.1:8080 -authSocket /Users/git/gitlab/tmp/sockets/gitlab.socket -documentRoot /Users/git/gitlab/public
```
⚠️ 注意该试验的 authBackend 设置为 http://127.0.0.1:8080   

1） 执行 /etc/init.d/gitlab start , 启动 nginx 后，用 80 端口和 8080 端口情况如下：
```shell
localhost-2:LaunchAgents XXXX$ sudo lsof -i tcp:80
Password:
COMMAND  PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
nginx   2439   root    8u  IPv4 0x8b1d16d89ac61e5f      0t0  TCP *:http (LISTEN)
nginx   2439   root    9u  IPv6 0x8b1d16d87f9ce6c7      0t0  TCP *:http (LISTEN)
nginx   2440 nobody    8u  IPv4 0x8b1d16d89ac61e5f      0t0  TCP *:http (LISTEN)
nginx   2440 nobody    9u  IPv6 0x8b1d16d87f9ce6c7      0t0  TCP *:http (LISTEN)
localhost-2:LaunchAgents XXXX$ sudo lsof -i tcp:8080
COMMAND  PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
ruby    6123  git   27u  IPv4 0x8b1d16d89ac31a7f      0t0  TCP localhost:http-alt (LISTEN)
ruby    6144  git   27u  IPv4 0x8b1d16d89ac31a7f      0t0  TCP localhost:http-alt (LISTEN)
ruby    6145  git   27u  IPv4 0x8b1d16d89ac31a7f      0t0  TCP localhost:http-alt (LISTEN)
ruby    7304  git   27u  IPv4 0x8b1d16d89ac31a7f      0t0  TCP localhost:http-alt (LISTEN)
```
2） 把 8080 端口对应的 ruby 进程 kill 掉，80 提供的服务是否还正常 ？  
发现：通过浏览器访问 GitLab 服务，报 502 。此时看 workhorse 的日志：  
```log
127.0.0.1  - - [2019/09/23:14:03:51 +0800] "GET / HTTP/1.1" 502 2940 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" 0.001
time="2019-09-23T14:03:51+08:00" level=error msg=error correlation_id=CoQ90iNyUS6 error="badgateway: failed after 0s: dial unix /Users/git/gitlab/tmp/sockets/gitlab.socket: connect: connection refused" method=GET uri=/favicon.ico
```
workhorse 与 8080 的 rails 服务之间的 socket 通信中断了。

3）把 8080 端口对应的 ruby 进程 kill 掉，http clone 的服务是否还正常 ？  
发现：也不正常。

**Comment by unaheidi** [comment]
#### 再来做个试验
上面我们把提供 8080 端口服务的进程给杀掉了，现在我们用 rails s 来恢复 8080 端口及其服务，看看情况会怎么样？

1）把 8080 端口对应的 ruby 进程恢复，80 提供的服务是否变正常 ？
仍然报错，原因是 ／Users/git/gitlab/tmp/sockets/gitlab.socket 这个文件的影子都没看见。
可想而知，http clone 的服务肯定也是失败的。

**Comment by unaheidi** [comment]
#### 继续做试验

我们不用 Rails s 来启动 web 服务，而是用 bin/web_puma 的方式来启动，用了自己定制的 /Users/git/gitlab/config/puma-for-development.rb 文件，该文件关键内容如下：
```ruby
# Bind the server to "url". "tcp://", "unix://" and "ssl://" are the only
# accepted protocols.
bind 'unix:///Users/git/gitlab/tmp/sockets/gitlab.socket'
```
启动方式如下：
```bash
bash-3.2$ RAILS_ENV=development bin/web_puma  start
[9015] * Listening on unix:///Users/git/gitlab/tmp/sockets/gitlab.socket
[9015] * Daemonizing...
```
8080端口当前没有恢复服务，只恢复了 socket 通信。
```shell
localhost-2:nodejs-ex100 XXXX$ sudo lsof -i tcp:8080
Password:
```
结果如下：
1）浏览器访问80端口，恢复正常。
2）http clone, 正常：
```bash
localhost-2:tmp XXXX$ git clone http://localhost/root/nodejs-ex100.git nodejs-tmp
Cloning into 'nodejs-tmp'...
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 46 (delta 20), reused 0 (delta 0)
remote:
Unpacking objects: 100% (46/46), done.
Checking out files: 100% (197/197), done.
```
3)  ssh clone，报错：
```bash
localhost-2:tmp XXXX$ git clone git@localhost:root/nodejs-ex100.git  nodejs-ssh
Cloning into 'nodejs-ssh'...
GitLab: Failed to authorize your Git request: internal API unreachable
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by unaheidi** [comment]
#### 如果把 gitlab-shell 的配置文件从 8080 改为 80，ssh clone 会成功吗 ？
试验结果：表明是成功的！
```bash
localhost-2:tmp XXXX$ git clone git@localhost:root/nodejs-ex100.git  nodejs-ssh
Cloning into 'nodejs-ssh'...
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 46 (delta 20), reused 0 (delta 0)
remote:
Receiving objects: 100% (46/46), 7.02 MiB | 15.37 MiB/s, done.
Resolving deltas: 100% (20/20), done.
```

**Comment by unaheidi** [comment]
#### 在8080不提供服务的情况下，workhorse 的 -authBackend http://127.0.0.1:8080  还有啥用途？
我发现，在这种情况下，Private 的仓库也能随便 clone 。(错觉，其实之前clone时输入了正确的用户名和密码所致)
```shell
localhost-2:tmp XXXX$ git clone http://localhost/root/nodejs-ex10.git  nedejs-ex10-http
Cloning into 'nedejs-ex10-http'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (6/6), done.
```
启动一个puma（env为development，仅提供socket），启动另一个puma（env为production，仅提供8080），不管通过浏览器访问80，还是http的clone，执行的结果都吐到 development.log 中。  

不禁有了一个想法，要不启动 workhorse 的时候，直接把  authBackend 设置为 http://127.0.0.1:80 ？或者干脆就不设置，怎么样？

**Comment by unaheidi** [comment]
#### 这没权限管控可不行，赶紧恢复 8080 试试看吧

**Comment by unaheidi** [comment]
#### 个人推测
其实 gitlab-shell 通过 Nginx 的 80 端口，Rails 服务不启用 8080 端口也可以。
可能是为了减少 gitlab-workhorse 的负担，提供 8080 端口服务后，gitlab-shell 就不用走 Nginx 那边了，可直接到 Rails 服务获取授权方面的信息。

**Comment by unaheidi** [comment]
#### 🍎 环境相关的事项，我想经过这段时间的琢磨，已经基本熟悉了。消停一下。

**Comment by unaheidi** [comment]
#### 有时候需要通过log的方式调试      
```ruby
def verify_api_request!(request_headers)
        #binding.pry
        Rails.logger.info("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n")
        Rails.logger.info(INTERNAL_API_REQUEST_HEADER)
        Rails.logger.info(request_headers[INTERNAL_API_REQUEST_HEADER])
```
