### ISSUE TITLE
[GitLab] Frontend环境 - 运行时调试

### ISSUE THREAD

**Issue by unaheidi** [unaheidi/it_ga_la#5]
#### 先看下面的文档
* [GitLab 前端团队介绍](https://about.gitlab.com/handbook/engineering/frontend/)
* [GitLab 前端团队Group](https://gitlab.com/gitlab-org/frontend)
* [GitLab 前端指南](https://gitlab.com/gitlab-org/frontend/general/issues/3)

#### Issue 对应的 Label 
* frontend

#### 前端测试标准和风格
[Testing standards and style guidelines](https://docs.gitlab.com/ee/development/testing_guide/index.html)
* unit and integration testing ：Jest , Karma and Jasmine for JavaScript .
* e2e (end-to-end) integration testing ：RSpec feature tests with Capybar .
* Unit and feature tests need to be written for all new features .
*  testing framework: Jest (/spec/frontend)

#### 代码和测试的对照表
[包含在 test level 的文章中 ](https://docs.gitlab.com/ee/development/testing_guide/testing_levels.html)

#### 挑选不同的测试 level

- Unit tests are usually cheap, and you should consider them like the basement of your house: you need them to be confident that your code is behaving correctly. However if you run only unit tests without integration / system tests, you might miss the big / picture !
- Integration tests are a bit more expensive, but don’t abuse them. A system test is often better than an integration test that is stubbing a lot of internals.
- System tests are expensive (compared to unit tests), even more if they require a JavaScript driver. Make sure to follow the guidelines in the Speed section.

#### 测试是有代价的

- The time it takes to write the test
- The time it takes to run the test every time the suite runs
- The time it takes to understand the test
- The time it takes to fix the test if it breaks and the underlying code is OK
- Maybe, the time it takes to change the code to make the code testable.

**Comment by unaheidi** [comment]
#### 测试最佳实践（精读）

**Comment by unaheidi** [comment]
#### Frontend testing standards and style guidelines （精读）

**Comment by unaheidi** [comment]
#### 设计模式 - Singletons 

GitLab 文档中提到，如果一个任务只需一个对象，宁可把它定义为 class ，而不要定义一个 object literal。

#### 前言
baidu上搜索 ‘前端设计模式 Singletons’，结果排名第一的这篇文档，我看得津津有味，当然，也看懂了。

早在2016年需要对Gerrit服务进行压力测试，我学javascript用它来写多个clone并发的测试脚本 。    
今年看[JS设计模式之单体模式（Singleton)](https://www.cnblogs.com/bloghxr/p/4459829.html) 这篇文档，没有什么问题，对于闭包、匿名函数并不陌生。

**新收获：**
* 什么叫 Lazy Load 或 按需加载？
* 怎么实现 Lazy Load 。

#### 检查一下是否真的理解 Singletons ？

GitLab 举了个例子告诉我们什么是好的做法，推荐我们采用 Singletons，代码如下：
```javascript
// bad

const MyThing = {
  prop1: 'hello',
  method1: () => {}
};

export default MyThing;

// good

class MyThing {
  constructor() {
    this.prop1 = 'hello';
  }
  method1() {}
}

export default new MyThing();

// best

export default class MyThing {
  constructor() {
    if (!this.prototype.singleton) {
      this.init();
      this.prototype.singleton = this;
    }
    return this.prototype.singleton;
  }

  init() {
    this.prop1 = 'hello';
  }

  method1() {}
}

``` 
分了 bad 、good 和 best 三种做法。

#### 体会三种做法的不同点
* bad 的这种方式，用的就是 an object literal ，它没有命名空间，这种方式需要开发人员注意，不要误用对象。

* good 的这种方式，为 best 的打好基础。用 class 来提供命名空间，如果重复定义是会报错的。

* best 的这种方式，真正确保一个类只有一个对象，使用的时候就是该对象，不会产生混淆。


#### 真正地体会
真的体会，当然不能只看看人家写的，人家说的，我喜欢动手自己实践。

##### 环境
javascript的运行环境，再和自己说一遍，除了使用 nodejs 运行环境外，还可以使用浏览器。  
* 可以用浏览器的开发者模式，在 Console 中直接写代码。
* 可以把代码写在 js 后缀的文件中，然后在 html 中添加该 js 文件，再用浏览器打开 html 文件。

##### 报错
```javascript
export default class MyThing {
  constructor() {
    if (!this.prototype.singleton) {
      this.init();
      this.prototype.singleton = this;
    }
    return this.prototype.singleton;
  }

  init() {
    this.prop1 = 'hello';
  }

  method1() {}
}
```

```html
<!DOCTYPE html>
<html>
<head>
    <title>Git Demo</title>
    <link rel="stylesheet" type="text/css" href="styles/style.css">
</head>
<body>
    <script src="js/my_thing.js"></script>
    <script src="js/her_thing.js"></script>
</body>
</html>

```

```javascript
Uncaught SyntaxError: Unexpected token export
```
![image](https://user-images.githubusercontent.com/4635811/65658353-e6c6a500-e059-11e9-9819-90abeb440046.png)

**Comment by unaheidi** [comment]
#### type=“module”

假如 index.html 如下：
```html
    <script type="module" src="js/my_thing.js" ></script>
    <script type="module" src="js/her_thing.js"></script>
```
Console 报错
```shell
Access to script at 'file:///Users/git/tmp/javascript_2019/js/my_thing.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.  
index.html:37 GET file:///Users/git/tmp/javascript_2019/js/my_thing.js net::ERR_FAILED
index.html:1 Access to script at 'file:///Users/git/tmp/javascript_2019/js/her_thing.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.  
index.html:38 GET file:///Users/git/tmp/javascript_2019/js/her_thing.js net::ERR_FAILED
```

**Comment by unaheidi** [comment]
#### type=“”
假如 index.html 如下：
```html
    <script type="module/javascript" src="js/my_thing.js" ></script>
    <script type="module/javascript" src="js/her_thing.js"></script>
```
Console 报错
![image](https://user-images.githubusercontent.com/4635811/65666034-66ab3a00-e06f-11e9-9a3c-64b513668db5.png)

**Comment by unaheidi** [comment]
## 搞不定啦，逼着我再找找学习资料吗？！

## 那是肯定的 😆

**Comment by unaheidi** [comment]
#### 前端开发☝️步（搭建模块运行环境）

1. 本来想偷个懒，把符合EC6支持class的代码直接存在 .js 文件中，然后用个 html 引入该 js 文件，再用chrome 以 file:/// 的方式访问 html 文件，直接 console 看各种设计模式的运行效果。
2. 事实说明上面的想法是不可行的。[报错](https://github.com/unaheidi/it_ga_la/issues/5#issuecomment-535368175)。
3. 上面 2 设想的方式行不同，那就用node + express运行个静态站点试试看吧。
     >  最贴切的参考 [《node + express 环境搭建参考》](https://blog.csdn.net/wenwushq/article/details/79827718)
4. 访问静态站点，发现还是报错，报错信息与1不同。无法访问到模块中的class。 
     > 其他人也遇到类似的问题，[参考文档。](https://stackoverflow.com/questions/53630310/use-functions-defined-in-es6-module-directly-in-html)

可能不是最佳的方法，但是毕竟达到了自己的目的：在 chrome 的 console 中已能够自如地调用 js 文件中的定义的 class ，并借此理解了 Singletons 的表现形式。 

#### 用于学习与体会的代码已经整理
[git 仓库](https://gitlab.com/dreamcoding/javascript/starter/tree/733193acecf56b5ea7ee20f9a753471a5d983af3)，供复习用。

#### 看 Singletons 的效果
MyThing 是个 Singletons 的类，而 HisThing 是普通的类。
```javascript
m1 = new MyThing
my_thing.js:3 MyThing {}
MyThing {prop1: "hello"}
m2 = new MyThing
my_thing.js:3 MyThing {}
MyThing {prop1: "hello"}
m1.prop1
"hello"
m1.prop1 = "Dear"
"Dear"
m2.prop1
"Dear"
```

```javascript
h1 = new HisThing
HisThing {prop1: "his llo"}
h2 = new HisThing
HisThing {prop1: "his llo"}
h1.prop1 = "llo his"
"llo his"
h2.prop1
"his llo"
```

```javascript
if(m1==m2) console.log("m1 is the same to m2")
VM516:1 m1 is the same to m2
undefined
if(h1==h2) console.log("h1 is the same to h2")
undefined
```

**Comment by unaheidi** [comment]
#### 终于可以回 GitLab 前端主题了

**Comment by unaheidi** [comment]
#### 思考
GitLab 官网对于前端初学者，并没有推荐上手的资料与方法。看了前辈们的指导，得有扎实的 html 、css 和 javascript 的功底。要不，静下心来学习学习看看？

**Comment by unaheidi** [comment]
#### 抓抓 CSS
搞清楚 [例子中](https://www.w3school.com.cn/tiy/t.asp?f=html5_html5_skeleton_2) <style> 里面的内容。  
😱 margin 和 padding ，真的很难懂吗？！
😱 display:inline 有啥功效？猜猜在哪里能找到它的说明？是“定位”，还是“对齐”，或是别的？最后还是在[“水平导航栏”](https://www.w3school.com.cn/css/css_navbar.asp)找到了它。

**Comment by unaheidi** [comment]
#### 再思考
是带着问题边干边学呢？还是找本书先啃？我尝试了看 w3chool 文档，我也尝试着找些前端的技术资料看，但我发现这样的效果并不好。原因是看的很肤浅，学了后面忘了前面，有些难的地方根本就看不懂。算了算了，还是带着解决实际问题的方式，边干边学吧。

### 从哪下手呢？
* GitLab前端的问题再多，可咱还得先找个容易搞定的（因为水平实在有限）。  
* 令我感到高兴的是，我有一个自己的需求，目前公司 GitLab 11.6 版本还没有这个功能，但是 GitLab.com 官网已经实现了该功能，而且，这个功能相对还是比较简单的。   
* 想到前几天，忙着找类似的情况，忙忙碌碌了一阵一点收获都没有，功能不是过于复杂就是功能不熟悉。这倒好，所谓 “柳暗花明又一村” 了，或者称作 “有心种花花不开，无心插柳柳成荫” 。

那到底是什么样的一个需求呢？
* 我近日把论坛的技术文档迁移到 GitLab ，用 Issue 来管理话题或文章。
* 在搬迁的过程中，我发现有些文档已经过时了，没必要放给开发人员查阅，但作为公司资产，这些文档还是有保留的价值的，因此，我把对应的 issues 设置了 confidential 属性，这样一来，开发人员就看不到这些 confidential 的 issues 了。
* 我用 Issue 的过滤功能，想快速找到自己需要的 issues ，但我在过滤条件中，发现缺少 “是否confidential” 的查询条件，在这种场景下，我认为这个过滤条件是非常有用的。
![image](https://user-images.githubusercontent.com/4635811/66457604-564d8300-eaa3-11e9-8f0c-9a37603fc81d.png)
* 果不其然，官网上最新版本已经有该功能了。
* 咱么就来看看，官网是如何实现的吧。:smile: :clap:

**Comment by unaheidi** [comment]
#### 从功能到代码
上面讲到我们已经找到了用来学习前端编程的功能点 —— issue过滤器中增加“是否confidential”的选项。下面我们得根据这个点找出对应的代码。那怎么才能较快地找到这些代码呢？方法如下：
* 根据web界面出现的 “confidential:” ，搜索哪些文件包含这个信息。  
   看着下面圈红的文件最像我们所需的。filtered_search 该文件夹代表了即有过滤又有搜索。  
![image](https://user-images.githubusercontent.com/4635811/66459998-a24ef680-eaa8-11e9-8e9d-def7bda58d95.png)
* 然后根据 “js-dropdown-confidential” ，看哪些文件包含该信息。
```js
      confidential: {
        reference: null,
        gl: DropdownNonUser,
        element: this.container.querySelector('#js-dropdown-confidential'),
      },
```
   结果如下：  
![image](https://user-images.githubusercontent.com/4635811/66460454-8ac43d80-eaa9-11e9-9b21-a7a9d977c03a.png)
* _search_bar_html.haml 文件中的代码和web界面的表现一摸一样。  
```haml
            #js-dropdown-confidential.filtered-search-input-dropdown-menu.dropdown-menu
              %ul.filter-dropdown{ data: { dropdown: true } }
                %li.filter-dropdown-item{ data: { value: 'yes', capitalize: true } }
                  %button.btn.btn-link{ type: 'button' }
                    = _('Yes')
                %li.filter-dropdown-item{ data: { value: 'no', capitalize: true } }
                  %button.btn.btn-link{ type: 'button' }
                    = _('No')
```
 * 仅仅看 _search_bar_html.haml 文件的变更还不够，我们应该顺藤摸瓜，找到对应的 Merge Request 和 Issue 。这样才能知道，如果要给过滤器增加额外的功能，完整的变更应该是什么样子的。

**Comment by unaheidi** [comment]
#### 从代码到 Merge Request 和 Issue
* 看 _search_bar_html.haml 该文件的 blame，找到变更对应的 commit 。
   https://gitlab.com/gitlab-org/gitlab/commit/a555a227dd7a846e5b8e8c84839120d40f9d1090
   commit 的 message 里面提供了后面的线索：See merge request gitlab-org/gitlab-ce!24960
* 继续找 Merge Request 。
   因为 gitlab-ce 的名称从 2019年9月 左右已变更为 gitlab-foss ，所以，对应的 merge request 的地址变为 https://gitlab.com/gitlab-org/gitlab-foss/merge_requests/24960
* 再看看有没有对应的 Issue 。
   该 MR 对应的 Issue ： https://gitlab.com/gitlab-org/gitlab-foss/issues/50747 。

**Comment by unaheidi** [comment]
#### 精读功能对应的需求，并通过 Merge Request 研究如何变更代码

**Comment by unaheidi** [comment]
#### 旁枝末节
看 Confidential 过滤功能的 Issue 的时候，又引出下面有意思的话题：  
* 之前 merge request 也有过滤需求，过滤出是否 WIP 的 Merge Requests。
* 引出了是否为 search 提供布尔查询的功能的。
* 是否需要重新设计 search 的模块。
   如果要学设计与开发的话，建议读一读 [Rethinking filters/search](https://gitlab.com/gitlab-org/gitlab-foss/issues/21747) 。

蛮有意思的。我们可以继续深入研究下面的 Issue 和 Merge Request：  
* issues/13650 [Filter merge requests that are marked WIP](https://gitlab.com/gitlab-org/gitlab-foss/issues/13650)
对应的 [merge_requests/18119](https://gitlab.com/gitlab-org/gitlab-foss/merge_requests/18119/diffs)
* issues/21747 [Rethinking filters/search](https://gitlab.com/gitlab-org/gitlab-foss/issues/21747)
对应的 [merge_requests/7345](https://gitlab.com/gitlab-org/gitlab-foss/merge_requests/7345/diffs#0758958f82f77950c7441a1b6cfbba6b95e35f2d)
* issues/27747 [](https://gitlab.com/gitlab-org/gitlab-foss/issues/27747)
* epics/291 [`not` and `or` in search and filter bars, including saved config in boards](https://gitlab.com/groups/gitlab-org/-/epics/291)
看来，搜索条件现在还不支持 not 、or 。

**Comment by unaheidi** [comment]
#### 和 search 和 filter 有关的代码（适合精读）

* 看 app/assets/javascripts/droplab 的变迁
https://gitlab.com/gitlab-org/gitlab-foss/commits/master/app/assets/javascripts/droplab
* 有个重构值得看，让代码模块化
https://gitlab.com/gitlab-org/gitlab-foss/commit/dab60475c79ff272c2a941326d609fed5fa4032e
* 除了 WIP 和 Confidential 的过滤外，再看看 ‘我不同反应’ 的过滤。
https://gitlab.com/gitlab-org/gitlab-foss/commit/7187395ef13d8d84a145d1b5251882ebada3f7f2

**Comment by unaheidi** [comment]
#### 还是回来着手实践吧

上面聊到可以精读的代码和设计讨论的过程，考虑到内容较多，暂时兜一圈稍微了解一下即可。  
下面我们还是结合 confidential 过滤这个功能，来看看具体实现吧

怎么做比较好呢？  
* 把 Merge Request 中变更的文件内容，一个一个地添加到我们自己的工程里面去。
* 中间报错的过程，我们可以一边理解代码之间谁依赖谁？一边理解每个变更的目的。

这个时候，之前 [搭建 GitLab 开发环境](https://github.com/unaheidi/it_ga_la/issues/4) 的准备工作，就显得非常有意义啦！ 😄 

马上行动，参考 https://github.com/unaheidi/it_ga_la/issues/5#issuecomment-539885130 。

**Comment by unaheidi** [comment]
#### 遇到的问题
* 修改 js 文件后，以“ rails_env=development  bundle exec rails s ” 启动 web 服务，chrome 开发者模式看 sources ，js 文件没有变化。
* 用 webpack-dev-server 方式启动 webpack 自带的服务，http://localhost:3808/ 查看，js 已经发生变化，但是 GitLab web 的 sources 中，js 文件仍然没有变化。
* 同事告诉我，得把 public/assets/webpack 文件夹删除，否则 web 服务回先到该路径找js文件，删除该文件夹后，web服务启动时报错。  
```log
Webpack::Rails::Manifest::ManifestLoadError - Could not load compiled manifest from /Users/git/gitlab/public/assets/webpack/manifest.json - have you run `rake webpack:compile`? (original error No such file or directory @ rb_sysopen - /Users/git/gitlab/public/assets/webpack/manifest.json):
  lib/gitlab/webpack/manifest.rb:13:in `entrypoint_paths'
  app/helpers/webpack_helper.rb:39:in `webpack_entrypoint_paths'
  app/helpers/webpack_helper.rb:22:in `webpack_controller_bundle_tags'
```
* 我猜并非删除 public/assets/webpack 该文件夹，估计需要修改指定 webpack 路径的配置文件。
一开始猜在 config/application.rb 文件中。
```ruby
    # Webpack dev server configuration is handled in initializers/static_files.rb
    config.webpack.dev_server.enabled = true
```
重启rails s 服务后，chrome 开发者模式看 sources ，js 文件还是没有变化。
* 又到 GitLab.com 官网上根据 ‘webpack dev server’ 搜索 issue ，看看有没有相关的话题，可以作为解决问题的突破点。
https://gitlab.com/gitlab-org/gitlab-foss/issues/27760
https://gitlab.com/gitlab-org/gitlab-foss/merge_requests/10604/diffs
找到一些线索。比如，里面提到 config/initializers/static_files.rb 这个文件，内有下面的代码：
```ruby
 if dev_server.enabled
    settings = {
      enabled: true,
      host: dev_server.host,
      port: dev_server.port,
      manifest_host: dev_server.host,
      manifest_port: dev_server.port
    }
```
我们不妨核对一下，我们启动服务的时候， dev_server.enabled 究竟是不是 true ？
*  赶紧请出 binding.pry 调试一下代码吧。
经过调试发现：如果把 application.rb 里面的  config.webpack.dev_server.enabled 从 false 改为 true，
执行 static_files.rb 的时候  dev_server.enabled 没有变成 true 。
* 再找找其他配置文件，看看在哪里设置才能真的启用 webpack.dev_server ？
后来修改了 1_settings.rb 后生效了。
```ruby
#
# Webpack settings
#
Settings['webpack'] ||= Settingslogic.new({})
Settings.webpack['dev_server'] ||= Settingslogic.new({})
Settings.webpack.dev_server['enabled'] ||= true
Settings.webpack.dev_server['host']    ||= 'localhost'
Settings.webpack.dev_server['port']    ||= 3808
```
* 不过有经验的那位同事，告诉我不应该在 1_settings.rb 文件里面改。  
   因为该文件是放在 git 仓库里面的，供任何环境使用的；应该在 gitlab.yml 文件中，应为该文件仅放在个人开发环境里面。于是，我修改了 gitlab.yml 的内容，把 webpack dev_server 相关行的注释去掉即可。


#### 前端代码变更后注意事项
* js文件变更后，只需要编译 changed 的文件，而不必花大把时间去编译所有的前端文件。
* GitLab 8.17 后改用了 webpack 构建前端。
  [Integrate webpack for frontend asset compilation](https://gitlab.com/gitlab-org/gitlab-foss/merge_requests/7288)
```shell
NODE_OPTIONS='--max_old_space_size=4096' ./node_modules/.bin/webpack-dev-server --config config/webpack.config.js
```

**Comment by unaheidi** [comment]
继续行动，参考 https://github.com/unaheidi/it_ga_la/issues/5#issuecomment-539885130 。

**Comment by unaheidi** [comment]
#### 代码之间的关系
* `_search_bar.html.haml`  和 `filtered_search_token_keys.js`  
注意：两个文件中 icon 、tag 

```haml
              %ul.filter-dropdown{ data: { dynamic: true, dropdown: true } }
                %li.filter-dropdown-item
                  %button.btn.btn-link{ type: 'button' }
                    -# Encapsulate static class name `{{icon}}` inside #{} to bypass
                    -# haml lint's ClassAttributeWithStaticValue
                    %svg
                      %use{ 'xlink:href': "#{'{{icon}}'}" }
                    %span.js-filter-hint
                      {{hint}}
                    %span.js-filter-tag.dropdown-light-content
                      {{tag}}
```
```js
  addExtraTokensForIssues() {
    const confidentialToken = {
      key: 'confidential',
      type: 'string',
      param: '',
      symbol: '',
      icon: 'eye-slash',
      tag: 'Yes or No',
      lowercaseValueOnSubmit: true,
      uppercaseTokenName: false,
      capitalizeTokenValue: true,
    };

    this.tokenKeys.push(confidentialToken);
    this.tokenKeysWithAlternative.push(confidentialToken);
  }

```
* `filtered_search_token_keys.js` 和  `index.js`
哪里调用了 addExtraTokensForIssues() 这个函数？
`app/assets/javascripts/pages/projects/issues/index/index.js`
```js
document.addEventListener('DOMContentLoaded', () => {
  IssuableFilteredSearchTokenKeys.addExtraTokensForIssues();
  
  initFilteredSearch({
    page: FILTERED_SEARCH.ISSUES,
    filteredSearchTokenKeys: IssuableFilteredSearchTokenKeys,
  });
  new IssuableIndex(ISSUABLE_INDEX.ISSUE);

  new ShortcutsNavigation();
  new UsersSelect();
});

```
* `_search_bar.html.haml`里面的 hint 变量从哪里来？为啥不是 key 呢？
来自：`dropdown_hint.js`
```js
  renderContent() {
    const dropdownData = this.tokenKeys.get().map(tokenKey => ({
      icon: `${gon.sprite_icons}#${tokenKey.icon}`,
      hint: tokenKey.key,
      tag: `:${tokenKey.tag}`,
      type: tokenKey.type,
    }));

    this.droplab.changeHookList(this.hookId, this.dropdown, [Filter], this.config);
    this.droplab.setData(this.hookId, dropdownData);
  }
```
* `_search_bar.html.haml` 文件里面已经写了下面的代码，为何界面没有出现 Yes 和 No 的按钮？
```haml
            #js-dropdown-confidential.filtered-search-input-dropdown-menu.dropdown-menu
              %ul.filter-dropdown{ data: { dropdown: true } }
                %li.filter-dropdown-item{ data: { value: 'yes', capitalize: true } }
                  %button.btn.btn-link{ type: 'button' }
                    = _('Yes')
                %li.filter-dropdown-item{ data: { value: 'no', capitalize: true } }
                  %button.btn.btn-link{ type: 'button' }
                    = _('No')
```
我估摸着应该是，这些按钮提供出来究竟有什么作用？需要和某个功能匹配在一起。
在 `filtered_search_dropdown_manager.js`这个文件中增加下面的代码即可：
```js
setupMapping() {
  const availableMappings = {
    confidential: {
        reference: null,
        gl: DropdownNonUser,
        element: this.container.querySelector('#js-dropdown-confidential'),
    },  
  }
}
```
为了搞懂这里面的关系，我感觉有必要学一下如何调试 javascript 。

**Comment by unaheidi** [comment]
#### 重启Mac后开发环境的准备

* 启动 DB 服务
* 启动 webpack-dev-server
* 启动 workhorse 、gitaly 和 sidekiq 服务
* 启动 rails s

**Comment by unaheidi** [comment]
#### javascript 的调试

* 在 js 文件中增加 debugger 就可以设置断点了。

* webpack.config.js 里面定义了 generateEntries ，会把各模块的 index.js 收集在一起，然后 export 给外部调用。  

* 调用顺序  
```
    index.js 
        --> init_filtered_search 
           --> filtered_search_manager.js  
                     'filteredSearchManager.setup()'  
                     "new FilteredSearchDropdownManager" 
           --> filtered_search_dropdown_manager.js "setupMapping() "
        --> IssuableFilteredSearchTokenKeys  "addExtraTokensForIssues()"
```
* 注意
   Confidential Yes 和 No 下拉列表的展示，代码实现在 filtered_search_manager.js  
   ```javascript  
  loadDropdown(dropdownName = '') {
    let firstLoad = false;

    if (!this.droplab) {
      firstLoad = true;
      this.droplab = new DropLab();
    }

    const match = this.filteredSearchTokenKeys.searchByKey(dropdownName.toLowerCase());
    const shouldOpenFilterDropdown =
      match && this.currentDropdown !== match.key && this.mapping[match.key];
    const shouldOpenHintDropdown = !match && this.currentDropdown !== 'hint';

    if (shouldOpenFilterDropdown || shouldOpenHintDropdown) {
      const key = match && match.key ? match.key : 'hint';
      this.load(key, firstLoad);
    }
  }
   ```

**Comment by unaheidi** [comment]
####  单元测试
暂停一下，后面再启动。
想把 git diff 的功能恢复一下。得先把 vue 相关的知识学习一下。
